#!/usr/bin/env python3
"""
export_thesis_table.py — Merge evaluation summaries for thesis tables.

Inputs (generated by existing scripts)
--------------------------------------
outputs/train_test_summary.csv   (from train_cnn.py)
outputs/compare_summary.csv      (from eval_compare.py)

Output
------
outputs/thesis_table_metrics.csv
"""

from __future__ import annotations

import csv
import os
from typing import Dict


SCRIPT_DIR = os.path.dirname(os.path.abspath(__file__))
OUT_DIR = os.path.join(SCRIPT_DIR, "outputs")

TRAIN_SUMMARY = os.path.join(OUT_DIR, "train_test_summary.csv")
COMPARE_SUMMARY = os.path.join(OUT_DIR, "compare_summary.csv")
THESIS_TABLE = os.path.join(OUT_DIR, "thesis_table_metrics.csv")


def _read_single_row_csv(path: str) -> Dict[str, str]:
    if not os.path.isfile(path):
        return {}
    with open(path, newline="", encoding="utf-8") as f:
        reader = csv.DictReader(f)
        for row in reader:
            return dict(row)
    return {}


def main() -> None:
    train = _read_single_row_csv(TRAIN_SUMMARY)
    comp = _read_single_row_csv(COMPARE_SUMMARY)

    if not train and not comp:
        raise FileNotFoundError(
            "No summary CSV found. Run one of:\n"
            "  python train_cnn.py\n"
            "  python eval_compare.py --mc-samples 30"
        )

    # Keep compact, thesis-friendly column names.
    row = {
        "eval_mode": comp.get("eval_mode", ""),
        "fusion_unc_scale": comp.get("fusion_unc_scale", ""),
        "cnn_test_mae_deg": train.get("test_mae_deg", ""),
        "cnn_p95_deg": train.get("p95_deg", ""),
        "cnn_p99_deg": train.get("p99_deg", ""),
        "cnn_small_lt1p5_mae_deg": train.get("small_lt1p5_mae_deg", ""),
        "cnn_large_gt3p5_mae_deg": train.get("large_gt3p5_mae_deg", ""),
        "cnn_mean_unc_deg": train.get("mean_unc_deg", ""),
        "cnn_within_1sigma_pct": train.get("within_1sigma_pct", ""),
        "cnn_within_2sigma_pct": train.get("within_2sigma_pct", ""),
        "fft_mae_deg": comp.get("fft_mae_deg", ""),
        "fft_p95_deg": comp.get("fft_p95_deg", ""),
        "fft_p99_deg": comp.get("fft_p99_deg", ""),
        "fft_small_lt1p5_mae_deg": comp.get("fft_small_lt1p5_mae_deg", ""),
        "fft_large_gt3p5_mae_deg": comp.get("fft_large_gt3p5_mae_deg", ""),
        "fft_fail_rate_pct": comp.get("fft_fail_rate_pct", ""),
        "mae_ratio_fft_over_cnn": comp.get("mae_ratio_fft_over_cnn", ""),
        "fusion_mae_deg": comp.get("fusion_mae_deg", ""),
        "fusion_p95_deg": comp.get("fusion_p95_deg", ""),
        "fusion_p99_deg": comp.get("fusion_p99_deg", ""),
    }

    os.makedirs(OUT_DIR, exist_ok=True)
    with open(THESIS_TABLE, "w", newline="", encoding="utf-8") as f:
        writer = csv.DictWriter(f, fieldnames=list(row.keys()))
        writer.writeheader()
        writer.writerow(row)

    print(f"Saved: {THESIS_TABLE}")


if __name__ == "__main__":
    main()

